unbind C-b
unbind r

set -g prefix C-d

set -g mouse on

set -g base-index 1
set -g status-position top
set -g status-left-length 20

set -g default-terminal "screen-256color" 
set -sa terminal-overrides ",tmux*:Tc" 



bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."
bind e command-prompt -p "Enter session name:" "new-session -s '%%'"
bind c command-prompt -p "Enter window name:" "new-window -n '%%'"

source-file ~/.tmux.theme
