# default statusbar colors
set-option -g status-style bg=colour0,fg=colour9

# default window title colors
set-window-option -g window-status-style fg=colour1,bg=default,dim

# active window title colors
set-window-option -g window-status-current-style fg=colour10,bg=default #84

# pane border
set-option -g pane-border-style fg=colour1
set-option -g pane-active-border-style fg=colour10 #84

# message text
set-option -g message-style bg=colour9,fg=colour0

# pane number display
set-option -g display-panes-active-colour colour10 #84
set-option -g display-panes-colour colour9

# clock
set-window-option -g clock-mode-colour colour9
