cursor_shape beam
cursor_shape_unfocused underline
                                                       
cursor_beam_thickness 1.5
cursor_underline_thickness 1.5

foreground #FFFFFF
background #0D0D0D

background_opacity 0.8
background_blur 1

color0 #141414
color1 #DC3232
color2 #32DC32
color3 #DCDC32
color4 #0064C8
color5 #DC32DC
color6 #32DCDC
color7 #DCDCDC

color8 #323232
color9 #FF3232
color10 #32FF32
color11 #FFFF32
color12 #0064FF
color13 #FF32FF
color14 #32FFFF
color15 #FFFFFF

font_family      CaskaydiaMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

enable_audio_bell no

window_margin_width 5

remember_window_size  no
initial_window_width  125c
initial_window_height 35c

confirm_os_window_close 0

copy_on_select yes
