pulse.rules = [
    {
        matches = [
            { application.process.binary = "chrome" }
            { application.process.binary = "Chromium input" }
            { application.process.binary = "Chromium" }
            { application.process.binary = "OBS" }
            { application.process.binary = "Discord" }
            { application.process.binary = "Vesktop" }
	        { application.process.binary = "firefox" }
        ]
        actions = { quirks = [ block-source-volume ] }
    }
]