[mgr]
show_hidden = true
show_symlink = true

[opener]
play = [
	{ run = 'xdg-open "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = 'nano "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

