$font = Monospace

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = easeOut
    animation = fadeIn, 1, 2, easeOut
    animation = fadeOut, 1, 2, easeOut
    animation = inputFieldDots, 1, 2, easeOut
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 1
    noise = 0
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.3)

    outer_color = rgba(1a1a1aee) rgba(4f4f4fee) 140deg
    check_color = rgba(fff200ee) rgba(c2ff33ee) 140deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 140deg

    font_color = rgba(255, 255, 255, 1)
    fade_on_empty = false
    rounding = 10

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    dots_text_format = *
    dots_size = 0.4
    dots_spacing = 0.3

    #hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font

    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 25
    font_family = $font

    position = -30, -150
    halign = right
    valign = top
}

label {
    monitor =
    text = $LAYOUT[it]
    font_size = 24
    onclick = hyprctl switchxkblayout all next

    position = 250, -20
    halign = center
    valign = center
}
